version: '3'
services:

  core-backend:
    container_name: core-backend
    restart: always
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    ports:
      - "8083:8080"
    command: mvn clean spring-boot:run
    depends_on:
      - core-mysql

  core-mysql:
    container_name: core-mysql
    image: mysql/mysql-server:5.7
    environment:
        MYSQL_DATABASE: root
        MYSQL_ROOT_PASSWORD: root
        MYSQL_ROOT_HOST: '%'
    ports:
      - "8086:3306"
    restart: always