
package com.xmlws.ftn.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SyncServicePortService", targetNamespace = "http://ftn.xmlws.com/soap", wsdlLocation = "http://172.18.0.1:8083/soapWS/core.wsdl")
public class SyncServicePortService
    extends Service
{

    private final static URL SYNCSERVICEPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SYNCSERVICEPORTSERVICE_EXCEPTION;
    private final static QName SYNCSERVICEPORTSERVICE_QNAME = new QName("http://ftn.xmlws.com/soap", "SyncServicePortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.18.0.1:8083/soapWS/core.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SYNCSERVICEPORTSERVICE_WSDL_LOCATION = url;
        SYNCSERVICEPORTSERVICE_EXCEPTION = e;
    }

    public SyncServicePortService() {
        super(__getWsdlLocation(), SYNCSERVICEPORTSERVICE_QNAME);
    }

    public SyncServicePortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SYNCSERVICEPORTSERVICE_QNAME, features);
    }

    public SyncServicePortService(URL wsdlLocation) {
        super(wsdlLocation, SYNCSERVICEPORTSERVICE_QNAME);
    }

    public SyncServicePortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SYNCSERVICEPORTSERVICE_QNAME, features);
    }

    public SyncServicePortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SyncServicePortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SyncServicePort
     */
    @WebEndpoint(name = "SyncServicePortSoap11")
    public SyncServicePort getSyncServicePortSoap11() {
        return super.getPort(new QName("http://ftn.xmlws.com/soap", "SyncServicePortSoap11"), SyncServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SyncServicePort
     */
    @WebEndpoint(name = "SyncServicePortSoap11")
    public SyncServicePort getSyncServicePortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://ftn.xmlws.com/soap", "SyncServicePortSoap11"), SyncServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SYNCSERVICEPORTSERVICE_EXCEPTION!= null) {
            throw SYNCSERVICEPORTSERVICE_EXCEPTION;
        }
        return SYNCSERVICEPORTSERVICE_WSDL_LOCATION;
    }

}
