
package com.xmlws.ftn.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SyncServicePort", targetNamespace = "http://ftn.xmlws.com/soap")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SyncServicePort {


    /**
     * 
     * @param getSyncRequest
     * @return
     *     returns com.xmlws.ftn.soap.GetSyncResponse
     */
    @WebMethod
    @WebResult(name = "getSyncResponse", targetNamespace = "http://ftn.xmlws.com/soap", partName = "getSyncResponse")
    public GetSyncResponse getSync(
        @WebParam(name = "getSyncRequest", targetNamespace = "http://ftn.xmlws.com/soap", partName = "getSyncRequest")
        GetSyncRequest getSyncRequest);

}
