INSTANCE_NO: 0
INSTANCE_DATABASE: localhost

spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: update

    datasource:
        url: ${DATABASE_SOURCE}
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver

    servlet:
      multipart:
        max-file-size: 200MB
        max-request-size: 200MB
