version: '3'
services:

  admin-backend:
    container_name: admin-backend
    restart: always
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    ports:
      - "8084:8080"
    command: mvn clean spring-boot:run
